	mysql --user=root --password=s3cr3t --host=localhost < create_db.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  grant_privileges.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  tbsecurity_status.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  tbsecurity_user.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  tbsecurity_role.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  tbsecurity_menu.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  tbsecurity_module.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  tbsecurity_rolemodule.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  tbsecurity_usermodule.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  tbsecurity_userrole.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_apply_userrole.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_delete_menu.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_delete_module.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_delete_rolemodule.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_delete_role.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_delete_usermodule.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_delete_user.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_get_assignedroles.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_get_availableroles.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_get_menulist.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_get_modulelist.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_get_rolelist.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_get_rolemodulelist.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_get_statuslist.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_get_userlist.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_get_usermodulelist.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_get_userrights.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_get_user.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_insert_menu.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_insert_module.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_insert_rolemodule.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_insert_role.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_insert_usermodule.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_insert_user.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_update_menu.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_update_module.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_update_rolemodule.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_update_role.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_update_usermodule.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  spsecurity_update_user.sql &
	mysql --user=root --password=s3cr3t --host=localhost sunny_prod_db <  vwsecurity_get_userrights.sql