/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package security.views;

import java.awt.GraphicsEnvironment;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import security.controllers.AppController;
import security.entities.User;
import security.entities.UserRight;
import security.models.ModuleModel;
import security.system.ConfigReader;

/**
 *
 * @author lespinoza
 */
public class AppSecurity extends javax.swing.JFrame {
    private final List<UserRight> rights;
    private AppController controller;

    /**
     * Creates new form JFrmDesktop
     */
    public AppSecurity() {
        LoginView lv = new LoginView(this, true);
        lv.setVisible(true);
        User user = lv.getAuthenticatedUser();
        rights = lv.getUserRights();
        initComponents();
        localInit(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPanel = new javax.swing.JDesktopPane();
        barMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPanelLayout = new javax.swing.GroupLayout(desktopPanel);
        desktopPanel.setLayout(desktopPanelLayout);
        desktopPanelLayout.setHorizontalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPanelLayout.setVerticalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        barMenu.add(jMenu1);

        jMenu2.setText("Edit");
        barMenu.add(jMenu2);

        setJMenuBar(barMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPanel)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppSecurity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AppSecurity().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JDesktopPane desktopPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables

    private void localInit(User user){
        String dbName = (new ConfigReader()).getApplicationDBName();
        this.setTitle("ESTO ERP - " + dbName);
        ModuleModel model = new ModuleModel();
        GraphicsEnvironment env =
        GraphicsEnvironment.getLocalGraphicsEnvironment();
        this.setMaximizedBounds(env.getMaximumWindowBounds());
        this.setExtendedState(this.getExtendedState() | AppSecurity.MAXIMIZED_BOTH);
        controller = new AppController(this, model, user, rights);
        loadMenu();
    }
    
     public void loadMenu(){
        barMenu.removeAll();
        
        // add menus
        UserRight previous = null;
        JMenu menu = null;
        for (UserRight current: rights){
            JMenuItem mnuItem = new JMenuItem();
            mnuItem.setText(current.getModule().getName());
            mnuItem.addActionListener(controller);
            mnuItem.setActionCommand("Action_" + String.valueOf(current.getModule().getId()));
                        
            if ( previous == null){
                menu =  new JMenu();
                menu.setText(current.getMenu().getName());
            }
            
            if ( previous != null && previous.getMenu().getId() != current.getMenu().getId()){
                barMenu.add(menu);
                menu =  new JMenu();
                menu.setText(current.getMenu().getName());
            } 
        
            menu.add(mnuItem);
            previous = current;
        }
        
        barMenu.add(menu);
        setJMenuBar(barMenu);
        pack();
    }
     
   public void addFrame(JInternalFrame frm){
     desktopPanel.add(frm);
   }
}
