mysql -u root -ppa$$w0rd esto_erp_db  < menu_options.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < tberp_country.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < tberp_address.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < tberp_contact.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < tberp_customer.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < tberp_customer_address.sq & 
mysql -u root -ppa$$w0rd esto_erp_db  < tberp_customer_contact.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < tberp_provider.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < tberp_provider_address.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < tberp_provider_contact.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_delete_customer.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_delete_customer_address.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_delete_customer_contact.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_delete_provider.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_delete_provider_address.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_delete_provider_contact.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_get_custumers.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_get_customer_addresses.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_get_customer_contacts.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_get_providers.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_get_provider_addresses.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_get_provider_contacts.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_insert_customer.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_insert_customer_address.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_insert_customer_contact.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_insert_provider.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_insert_provider_address.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_insert_provider_contact.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_update_address.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_update_contact.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_update_customer.sql & 
mysql -u root -ppa$$w0rd esto_erp_db  < sperp_update_provider.sql & 

