
mysql -u root -ppa$$w0rd < create_db.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  tbsecurity_status.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  tbsecurity_user.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  tbsecurity_role.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  tbsecurity_menu.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  tbsecurity_module.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  tbsecurity_rolemodule.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  tbsecurity_usermodule.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  tbsecurity_userrole.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Apply_UserRole.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Delete_Menu.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Delete_Module.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Delete_RoleModule.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Delete_Role.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Delete_UserModule.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Delete_User.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Get_AssignedRoles.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Get_AvailableRoles.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Get_MenuList.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Get_ModuleList.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Get_RoleList.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Get_RoleModuleList.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Get_StatusList.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Get_UserList.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Get_UserModuleList.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Get_UserRights.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Get_User.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Insert_Menu.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Insert_Module.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Insert_RoleModule.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Insert_Role.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Insert_UserModule.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Insert_User.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Update_Menu.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Update_Module.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Update_RoleModule.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Update_Role.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Update_UserModule.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  spSecurity_Update_User.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  vwSecurity_Get_UserRights.sql & 
mysql -u root -ppa$$w0rd esto_erp_db <  grant_privileges.sql
