/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp.container;

import erp.entities.Submaterial;
import erp.views.SubmaterialView;
import security.entities.User;
import security.entities.UserRight;

/**
 *
 * @author lespinoza
 */
public class SubmaterialContainer extends javax.swing.JInternalFrame {
    private SubmaterialView submaterialView;
    
    /**
     * Creates new form CustomerView2
     * @param user
     * @param right
     */
    public SubmaterialContainer(User user, UserRight right) {
        initComponents();
        localInit(user, right);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        pnlCatalog = new javax.swing.JPanel();
        pnlProviders = new javax.swing.JPanel();
        pnlCosts = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Submaterials");

        javax.swing.GroupLayout pnlCatalogLayout = new javax.swing.GroupLayout(pnlCatalog);
        pnlCatalog.setLayout(pnlCatalogLayout);
        pnlCatalogLayout.setHorizontalGroup(
            pnlCatalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlCatalogLayout.setVerticalGroup(
            pnlCatalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Catalog", pnlCatalog);

        javax.swing.GroupLayout pnlProvidersLayout = new javax.swing.GroupLayout(pnlProviders);
        pnlProviders.setLayout(pnlProvidersLayout);
        pnlProvidersLayout.setHorizontalGroup(
            pnlProvidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlProvidersLayout.setVerticalGroup(
            pnlProvidersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Providers", pnlProviders);

        javax.swing.GroupLayout pnlCostsLayout = new javax.swing.GroupLayout(pnlCosts);
        pnlCosts.setLayout(pnlCostsLayout);
        pnlCostsLayout.setHorizontalGroup(
            pnlCostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlCostsLayout.setVerticalGroup(
            pnlCostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Cost", pnlCosts);

        jLabel1.setText("Code:");

        txtCode.setEditable(false);

        jLabel2.setText("Submaterial:");

        txtDescription.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescription)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel pnlCatalog;
    private javax.swing.JPanel pnlCosts;
    private javax.swing.JPanel pnlProviders;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDescription;
    // End of variables declaration//GEN-END:variables

    private void localInit(User user, UserRight right) {
        submaterialView = new SubmaterialView(user, right);
        
        this.pnlCatalog.setLayout(new java.awt.BorderLayout());
        this.pnlCatalog.add(submaterialView);
        this.pnlCatalog.revalidate(); 
        
        Submaterial selectedSubmaterial;
        selectedSubmaterial = submaterialView.getSelectedItem();
        if (selectedSubmaterial == null){
            txtCode.setText("");
            txtDescription.setText("");
        } else {
            txtCode.setText(selectedSubmaterial.getCode());
            txtDescription.setText(selectedSubmaterial.getDescription());
        }
    }
}
